### ISSUE TITLE
ValueError: Expected object or value

### ISSUE THREAD

**Issue by bf-yang** [Itaymanes/K-QA#2]
When I run:
python K-QA/run_eval.py --result_file K-QA/dummy_res.json --version test0

It reports the following error:
Traceback (most recent call last):
  File "/home/bufang/langchain-rag-tutorial/K-QA/run_eval.py", line 157, in <module>
    asyncio.run(
  File "/home/bufang/anaconda3/envs/rag/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/bufang/anaconda3/envs/rag/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bufang/langchain-rag-tutorial/K-QA/run_eval.py", line 32, in run_experiment
    df_gt = pd.read_json(
  File "/home/bufang/anaconda3/envs/rag/lib/python3.10/site-packages/pandas/io/json/_json.py", line 815, in read_json
    return json_reader.read()
  File "/home/bufang/anaconda3/envs/rag/lib/python3.10/site-packages/pandas/io/json/_json.py", line 1023, in read
    obj = self._get_object_parser(self._combine_lines(data_lines))
  File "/home/bufang/anaconda3/envs/rag/lib/python3.10/site-packages/pandas/io/json/_json.py", line 1051, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/bufang/anaconda3/envs/rag/lib/python3.10/site-packages/pandas/io/json/_json.py", line 1187, in parse
    self._parse()
  File "/home/bufang/anaconda3/envs/rag/lib/python3.10/site-packages/pandas/io/json/_json.py", line 1427, in _parse
    ujson_loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value

**Comment by Itaymanes** [comment]
Hi,

Thank you for opening this issue. Please correct me if I am wrong, but I assume you simply didn't execute the script from the correct directory.

In the terminal, you can follow these steps:

```bash
git clone git@github.com:Itaymanes/K-QA.git
cd K-QA
```

Then, install the relevant packages. We use `poetry` as we have found it more convenient for obtaining the necessary requirements. Additionally, add the relevant environment keys for azure or openai.

Finally, execute the following command:

```bash
python run_eval.py --result_file dummy_res.json --version test0
```

**Comment by bf-yang** [comment]
Thanks for your reply. Now it works for me. Thanks~
